### ISSUE TITLE
We need to make library unittestable

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#73]
We have configured sending coverage information to codecov.io, but the problem is that we are right now no able to run istanbul, because there are some symbols that are not initialized.

During testing I've got:
/home/magul/Dokumenty/komitywa/plantingjs/src/js/app.js:9
b['1'][1]++;}}.bind(this));};__cov_Ezz5ge$ARayUr8xjqaPfqQ.s['56']++;_.extend(P
                                                                    ^
ReferenceError: _ is not defined
    at Object.<anonymous> (/home/magul/Dokumenty/komitywa/plantingjs/src/js/app.js:9:5630)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions.(anonymous function) [as .js](/home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/magul/Dokumenty/komitywa/plantingjs/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/magul/Dokumenty/komitywa/plantingjs/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/magul/Dokumenty/komitywa/plantingjs/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js](/home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (/home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:363:13
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:248:21)
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/magul/Dokumenty/komitywa/plantingjs/node_modules/istanbul/node_modules/async/lib/async.js:360:17
    at LOOP (fs.js:1474:14)
    at process._tickCallback (node.js:355:11)

**Comment by magul** [comment]
In this task commented command in travis.yml should be uncommented.
